### PR TITLE
[JENKINS-55955] Remove JAXB dependency from Notification

### PR DESCRIPTION
**Pull request by basil**
Fixes [JENKINS-55955](https://issues.jenkins.io/browse/JENKINS-55955).

CC @hagzag @cohencil

### CODE REVIEW

**Review by hagzag — APPROVED** [review]

**Comment by basil** [comment]
@hagzag 1.16 is not showing up on [the Update Center](https://plugins.jenkins.io/notification/). Are you sure you performed the release correctly?

**Comment by basil** [comment]
@hagzag Thank you for merging and releasing this pull request. I highly appreciate your diligence in maintaining this plugin. As a gentle reminder, we are planning on requiring Java 11 in the Jenkins weekly release line as of June 21, 2022. Ideally, we would be able to release this plugin prior to that date to ensure a smooth experience for users of the weekly release line.

**Comment by hagzag** [comment]
I was removed from the maintainers list so I can't release will investigate
later whos the " new releaser"

**Comment by basil** [comment]
> I was removed from the maintainers list

I am not sure where you got that impression from, but it is not accurate. You are still listed as having repository permissions:

https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-notification.yml

To reset your credentials:

https://accounts.jenkins.io/

For documentation:

https://www.jenkins.io/doc/developer/publishing/releasing-manually/

**Comment by hagzag** [comment]
Ok, I'll check it out tomorrow.

**Comment by basil** [comment]
@hagzag it looks like an attempt to perform a release was made in https://github.com/jenkinsci/notification-plugin/releases/tag/notification-1.16 but there is no 1.16 release visible on the Plugin Site or on Artifactory:

- https://plugins.jenkins.io/notification/
- https://repo.jenkins-ci.org/artifactory/releases/com/tikalk/hudson/plugins/notification/

Were you able to reset your credentials and perform a release? Let us know if we can help. To reset your credentials: https://accounts.jenkins.io/ For documentation: https://www.jenkins.io/doc/developer/publishing/releasing-manually/

**Comment by basil** [comment]
Hi @hagzag, gentle ping about performing this release. Is there anything we can do to help?

**Pull request merged**
