### PR TITLE
Fixed missed folder defined credentials

### PR DESCRIPTION
**Pull request by reinhapa**
Fixes credentials defined on folders are not taken into account.

### CODE REVIEW

**Comment by reinhapa** [comment]
@hagzag any chance to get this and #42 merged by any chance?

**Comment by cohencil** [comment]
@reinhapa resolve conflicts to get it merged

**Comment by reinhapa** [comment]
@cohencil merge done

**Comment by reinhapa** [comment]
@cohencil thanks. looking forward to the next release...

**Pull request merged**
