### PR TITLE
Add build duration to job notification

### PR DESCRIPTION
**Pull request by ardakuyumcu**
Adding the run duration to the build state model.

### CODE REVIEW

**Comment by ardakuyumcu** [comment]
@cohencil sorry to tag you directly, I couldn't find any documentation around how to call attention to pull requests. I would appreciate any feedback and help getting this change merged in, thanks!

**Comment by ardakuyumcu** [comment]
@mark2b @hagzag you're also listed as maintainers here under https://plugins.jenkins.io/notification

Any chance you're able to help?

**Comment by ardakuyumcu** [comment]
@hagzag hi, I noticed the repo is no longer dormant. Would you be able to review this PR for me? Thanks a lot!

**Review by hagzag — COMMENTED** [review]
LGTM

**Pull request merged**
