### PR TITLE
JENKINS-30731: added support for Build start time and Build duration

### PR DESCRIPTION
**Pull request by dshvedchenko**

### CODE REVIEW

**Comment by stjohnjohnson** [comment]
:+1: This would be fantastic!!!! 

What do we need to do to get this merged?
giphy 3

**Comment by afbjorklund** [comment]
I made a version of this in #26, that uses millisecond timestamps instead of strings and durations.
It also adds the queue time statistic, so that you can tell how long builds were being queued for.

**Comment by bvamos** [comment]
Please merge this

**Comment by cohencil** [comment]
Closing this pr as functionality is covered in merged pr #26

**Pull request closed without merging**
