### PR TITLE
[JENKINS-30599] Add Failure Notification

### PR DESCRIPTION
**Pull request by kristenoliphant**
Added a notification only on failure

### CODE REVIEW

**Comment by khasinski** [comment]
:+1: Also waiting for that PR to be merged.

**Comment by hgontijo** [comment]
That's a great feature, thank you! Any plans to release it?

**Comment by thatarchguy** [comment]
+1 This is perfect

**Comment by knehring** [comment]
+1 on this feature this would be perfect for some of our use cases

**Comment by joemar1988** [comment]
+1 on this feature as well. Definitely needed.

**Pull request merged**
